spring.application.name=a2a-server
server.port=28080
#spring.ai.openai.base-url=${OPENAI_BASE_URL}
#spring.ai.openai.api-key=${OPENAI_API_KEY}
#spring.ai.openai.chat.options.model=${OPENAI_CHAT_MODEL}
spring.ai.dashscope.api-key=${AI_DASHSCOPE_API_KEY}
